### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by kevinMintnick** [power721/oj#15]
Error: package com.jfinal.aop does not exist
=========
jdk1.8

**Comment by w703710691d** [comment]
Make sure you load all package in pom.xml?

**Comment by kevinMintnick** [comment]
On the left side of the idea editor, can see the loaded packages, such as jfinal's.

But still unable to compile

**Comment by kevinMintnick** [comment]
Is it convenient to provide specific development environment?
Such as JDK version, development editor

**Comment by w703710691d** [comment]
this package in jfinal-2.2.jar，have you find this file？

**Comment by kevinMintnick** [comment]
Thank you very much for your answer. The problem has been solved.

**Comment by kevinMintnick** [comment]
However, why can't I add questions in the background?

**Comment by w703710691d** [comment]
you may don't have perrmision to access problem file
see the var Data Directory in background info page  , tomcat should have perrmision to write in those dir。 More information, please see tomcat log :)

**Comment by kevinMintnick** [comment]
Create a question tip in the background
I use windows 10 system. Do I need to make any changes?
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
	at com.power.oj.problem.ProblemService.addProblem(ProblemService.java:420)
	at com.power.oj.admin.ProblemAdminController.save(ProblemAdminController.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.jfinal.ext.interceptor.POST.intercept(POST.java:30)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.ext.plugin.shiro.ShiroInterceptor.intercept(ShiroInterceptor.java:51)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.user.UserInterceptor.intercept(UserInterceptor.java:30)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.core.interceptor.AccessLogInterceptor.intercept(AccessLogInterceptor.java:41)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.core.interceptor.SessionAttrInterceptor.intercept(SessionAttrInterceptor.java:30)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.core.interceptor.OjVariableInterceptor.intercept(OjVariableInterceptor.java:12)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.core.interceptor.GlobalInterceptor.intercept(GlobalInterceptor.java:35)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.power.oj.core.interceptor.TimingInterceptor.intercept(TimingInterceptor.java:18)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:77)
	at com.jfinal.plugin.druid.DruidStatViewHandler.handle(DruidStatViewHandler.java:75)
	at com.power.oj.core.handler.UrlFilterHandler.handle(UrlFilterHandler.java:21)
	at com.power.oj.core.handler.BaseUrlHandler.handle(BaseUrlHandler.java:28)
	at com.power.oj.core.handler.SessionHandler.handle(SessionHandler.java:21)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by w703710691d** [comment]
please use linux system such as ubuntu

**Comment by kevinMintnick** [comment]
Is the web and the judge in the Linux environment？
